package models

type SCMetadata struct {
	SCID                  string
	SCName                string
	Level                 string // "A" | "AA"
	WCAGVersion           string // "2.0" | "2.1" | "2.2"
	EN301549Clause        string // "9.x.x.x"; empty for non-web clauses
	SupportNarrative      string // Remarks text when Conformance == Supports
	PartialNarrative      string // Remarks text when Conformance == PartiallySupports
	FailureNarrative      string // Remarks text when Conformance == DoesNotSupport
	LimitationNote        string // Always appended; describes automation limits
	ManualTestingRequired bool
	NotAutomatable        bool // true = always NotEvaluated; no rule can exist
}

var SCRegistry = map[string]SCMetadata{
	"1.1.1": {
		SCID: "1.1.1", SCName: "Non-text Content", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.1.1",
		SupportNarrative:      "Automated testing checked all img, input[type=image], and icon elements for programmatic text alternatives. All tested elements passed.",
		PartialNarrative:      "Some images or interactive elements are missing text alternatives. See violation details for affected elements.",
		FailureNarrative:      "A majority of tested elements lack adequate text alternatives, representing a significant barrier for screen reader users.",
		LimitationNote:        "Complex images (charts, infographics) require manual review to verify that alternative text is accurate and meaningful. CAPTCHA alternatives require manual evaluation.",
		ManualTestingRequired: true,
	},
	"1.2.1": {
		SCID: "1.2.1", SCName: "Audio-only and Video-only (Prerecorded)", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.2.1",
		SupportNarrative:      "Automated testing detected prerecorded audio/video elements and verified the presence of text transcripts or audio descriptions.",
		PartialNarrative:      "Some prerecorded media elements lack accompanying text alternatives.",
		FailureNarrative:      "Prerecorded media lacks required text alternatives.",
		LimitationNote:        "Automated testing can detect presence of transcripts but cannot verify their accuracy or completeness.",
		ManualTestingRequired: true,
	},
	"1.2.2": {
		SCID: "1.2.2", SCName: "Captions (Prerecorded)", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.2.2",
		SupportNarrative:      "All detected video elements include caption tracks with valid source and language attributes.",
		PartialNarrative:      "Some video elements are missing caption tracks or have incomplete track attributes.",
		FailureNarrative:      "Most video elements lack caption tracks, preventing access for deaf and hard-of-hearing users.",
		LimitationNote:        "Automated testing verifies presence and attributes of <track kind=\"captions\"> elements but cannot verify caption timing accuracy or synchronization.",
		ManualTestingRequired: true,
	},
	"1.2.3": {
		SCID: "1.2.3", SCName: "Audio Description or Media Alternative (Prerecorded)", Level: "A", WCAGVersion: "2.0",
		EN301549Clause: "9.1.2.3",
		LimitationNote: "Requires manual evaluation to verify that a media alternative or audio description is present and adequate.",
		NotAutomatable: true,
	},
	"1.2.4": {
		SCID: "1.2.4", SCName: "Captions (Live)", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.1.2.4",
		LimitationNote: "Live captions cannot be evaluated by automated scanning. Manual testing is required during live broadcasts or streaming events.",
		NotAutomatable: true,
	},
	"1.2.5": {
		SCID: "1.2.5", SCName: "Audio Description (Prerecorded)", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.2.5",
		LimitationNote:        "Determining whether audio descriptions exist and are adequate requires manual review of video content with an audio specialist. Automated scanning cannot evaluate audio description quality or completeness.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"1.3.1": {
		SCID: "1.3.1", SCName: "Info and Relationships", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.3.1",
		SupportNarrative:      "Automated testing verified landmark structure, form label associations, list semantics, heading hierarchy, table markup, and ARIA role usage.",
		PartialNarrative:      "Some interface elements convey structure through visual presentation alone without programmatic equivalents.",
		FailureNarrative:      "Significant structural information is conveyed through visual presentation without programmatic markup.",
		LimitationNote:        "CSS-only layout patterns and complex data tables require manual verification.",
		ManualTestingRequired: true,
	},
	"1.3.2": {
		SCID: "1.3.2", SCName: "Meaningful Sequence", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.3.2",
		SupportNarrative:      "DOM order and reading sequence appear programmatically correct.",
		PartialNarrative:      "Some content may be presented in a reading order that differs from visual order.",
		FailureNarrative:      "Content reading sequence is not correctly programmatically determinable.",
		LimitationNote:        "Complex layout patterns require manual screen reader verification.",
		ManualTestingRequired: true,
	},
	"1.3.3": {
		SCID: "1.3.3", SCName: "Sensory Characteristics", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.3.3",
		SupportNarrative:      "Instructions do not rely solely on sensory characteristics.",
		PartialNarrative:      "Some instructions may rely solely on shape, size, color, or spatial location.",
		FailureNarrative:      "Instructions rely solely on sensory characteristics without text alternatives.",
		LimitationNote:        "Requires manual review of instructional content.",
		ManualTestingRequired: true,
	},
	"1.3.4": {
		SCID: "1.3.4", SCName: "Orientation", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.3.4",
		SupportNarrative:      "No orientation lock detected in CSS or JavaScript event handlers.",
		PartialNarrative:      "Orientation restrictions were detected in some contexts.",
		FailureNarrative:      "Content restricts display to a single orientation.",
		LimitationNote:        "Dynamic orientation locking triggered by specific interactions requires manual device testing.",
		ManualTestingRequired: true,
	},
	"1.3.5": {
		SCID: "1.3.5", SCName: "Identify Input Purpose", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.3.5",
		SupportNarrative:      "Form inputs use appropriate autocomplete attribute values.",
		PartialNarrative:      "Some form inputs are missing appropriate autocomplete attributes.",
		FailureNarrative:      "Form inputs lack autocomplete attributes that would allow browsers to auto-fill personal data.",
		LimitationNote:        "Effectiveness of autocomplete tokens requires testing with browser autofill tools.",
		ManualTestingRequired: false,
	},
	"1.4.1": {
		SCID: "1.4.1", SCName: "Use of Color", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.4.1",
		SupportNarrative:      "No instances detected where color is the sole visual indicator of information.",
		PartialNarrative:      "Some elements may rely on color alone to convey information.",
		FailureNarrative:      "Color is used as the sole visual means of conveying information.",
		LimitationNote:        "Complex charts, graphs, and custom UI patterns require manual review.",
		ManualTestingRequired: true,
	},
	"1.4.2": {
		SCID: "1.4.2", SCName: "Audio Control", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.4.2",
		LimitationNote:        "Determining whether auto-playing audio lasts more than 3 seconds and whether a control mechanism is available requires live interaction testing. Automated scanning cannot reliably detect or evaluate audio playback controls.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"1.4.3": {
		SCID: "1.4.3", SCName: "Contrast (Minimum)", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.4.3",
		SupportNarrative:      "All tested text elements meet the 4.5:1 contrast ratio requirement (3:1 for large text).",
		PartialNarrative:      "Some text elements fail the minimum contrast ratio. See violation details.",
		FailureNarrative:      "Widespread contrast failures detected. Text readability is significantly impacted for low-vision users.",
		LimitationNote:        "Contrast of text rendered on dynamic or image backgrounds requires manual evaluation. Semi-transparent overlays may not be detected.",
		ManualTestingRequired: true,
	},
	"1.4.4": {
		SCID: "1.4.4", SCName: "Resize Text", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.1.4.4",
		SupportNarrative:      "No CSS preventing text scaling detected.",
		PartialNarrative:      "Some CSS may restrict text resizing.",
		FailureNarrative:      "CSS detected that prevents text from scaling up to 200% without loss of content or functionality.",
		LimitationNote:        "Text resize behavior at 200% requires manual browser testing.",
		ManualTestingRequired: true,
	},
	"1.4.5": {
		SCID: "1.4.5", SCName: "Images of Text", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.1.4.5",
		LimitationNote: "Detecting images that contain text requires visual analysis not achievable by DOM inspection alone. Manual review required.",
		NotAutomatable: true,
	},
	"1.4.10": {
		SCID: "1.4.10", SCName: "Reflow", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.4.10",
		SupportNarrative:      "No CSS preventing content reflow at 320px width detected.",
		PartialNarrative:      "Some layout patterns may cause horizontal scrolling at 320px equivalent width.",
		FailureNarrative:      "Horizontal scrolling is required at 320px CSS width, preventing access for users relying on reflow.",
		LimitationNote:        "Reflow testing requires manual verification at 320px CSS width.",
		ManualTestingRequired: true,
	},
	"1.4.11": {
		SCID: "1.4.11", SCName: "Non-text Contrast", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.4.11",
		SupportNarrative:      "UI component boundaries and graphical objects meet the 3:1 contrast ratio.",
		PartialNarrative:      "Some UI components or graphical objects do not meet the 3:1 contrast ratio.",
		FailureNarrative:      "Widespread non-text contrast failures detected.",
		LimitationNote:        "Focus indicators and complex graphical objects require manual contrast evaluation.",
		ManualTestingRequired: true,
	},
	"1.4.12": {
		SCID: "1.4.12", SCName: "Text Spacing", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.4.12",
		SupportNarrative:      "No CSS that prevents text spacing overrides detected.",
		PartialNarrative:      "Some CSS may cause layout breakage when text spacing properties are applied.",
		FailureNarrative:      "CSS prevents content and functionality from being accessible when text spacing properties are overridden.",
		LimitationNote:        "Requires manual testing by applying the text spacing bookmarklet.",
		ManualTestingRequired: true,
	},
	"1.4.13": {
		SCID: "1.4.13", SCName: "Content on Hover or Focus", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.1.4.13",
		SupportNarrative:      "Hover and focus-triggered content is dismissible, hoverable, and persistent.",
		PartialNarrative:      "Some hover or focus-triggered content may not meet all three requirements.",
		FailureNarrative:      "Hover or focus-triggered content cannot be dismissed, hovered over, or persists only briefly.",
		LimitationNote:        "Requires manual interaction testing with keyboard and mouse.",
		ManualTestingRequired: true,
	},
	"2.1.1": {
		SCID: "2.1.1", SCName: "Keyboard", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.1.1",
		SupportNarrative:      "All interactive elements are keyboard accessible.",
		PartialNarrative:      "Some interactive functionality is not fully keyboard accessible.",
		FailureNarrative:      "Keyboard-only users cannot access significant functionality.",
		LimitationNote:        "Complete keyboard navigation testing requires manual keyboard-only interaction across all interactive features.",
		ManualTestingRequired: true,
	},
	"2.1.2": {
		SCID: "2.1.2", SCName: "No Keyboard Trap", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.1.2",
		SupportNarrative:      "No keyboard traps detected in automated testing.",
		PartialNarrative:      "Potential keyboard traps detected in some components.",
		FailureNarrative:      "Keyboard trap(s) detected that prevent users from navigating away from a component.",
		LimitationNote:        "Keyboard trap detection requires manual keyboard testing of modal dialogs, date pickers, and custom widgets.",
		ManualTestingRequired: true,
	},
	"2.1.4": {
		SCID: "2.1.4", SCName: "Character Key Shortcuts", Level: "A", WCAGVersion: "2.1",
		EN301549Clause:        "9.2.1.4",
		LimitationNote:        "Determining whether single-character keyboard shortcuts exist and whether they can be remapped or disabled requires manual interaction with the running application. Automated DOM scanning cannot observe runtime keyboard event behaviour.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"2.2.1": {
		SCID: "2.2.1", SCName: "Timing Adjustable", Level: "A", WCAGVersion: "2.0",
		EN301549Clause: "9.2.2.1",
		LimitationNote: "Detecting time limits and evaluating adjustment mechanisms requires manual testing during user session interactions.",
		NotAutomatable: true,
	},
	"2.2.2": {
		SCID: "2.2.2", SCName: "Pause, Stop, Hide", Level: "A", WCAGVersion: "2.0",
		EN301549Clause: "9.2.2.2",
		LimitationNote: "Detecting moving, blinking, or scrolling content and verifying pause controls requires manual testing.",
		NotAutomatable: true,
	},
	"2.3.1": {
		SCID: "2.3.1", SCName: "Three Flashes or Below Threshold", Level: "A", WCAGVersion: "2.0",
		EN301549Clause: "9.2.3.1",
		LimitationNote: "Requires specialized photosensitivity analysis tools. Automated DOM scanning cannot evaluate flash rate or duration.",
		NotAutomatable: true,
	},
	"2.4.1": {
		SCID: "2.4.1", SCName: "Bypass Blocks", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.1",
		SupportNarrative:      "Skip navigation links or ARIA landmark regions are present, enabling users to bypass repetitive content.",
		PartialNarrative:      "Bypass mechanisms exist but may be inconsistently implemented.",
		FailureNarrative:      "No bypass mechanism detected; keyboard-only users must tab through all navigation on every page.",
		LimitationNote:        "Effectiveness of bypass mechanisms requires manual keyboard testing.",
		ManualTestingRequired: true,
	},
	"2.4.2": {
		SCID: "2.4.2", SCName: "Page Titled", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.2",
		SupportNarrative:      "Page has a descriptive <title> element.",
		PartialNarrative:      "Page title is present but may not adequately describe the page topic or purpose.",
		FailureNarrative:      "Page is missing a <title> element or has an empty title.",
		LimitationNote:        "Title adequacy (whether it describes topic and purpose) requires manual review.",
		ManualTestingRequired: false,
	},
	"2.4.3": {
		SCID: "2.4.3", SCName: "Focus Order", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.3",
		SupportNarrative:      "Focus order appears to preserve meaning and operability.",
		PartialNarrative:      "Focus order may be disrupted in some sections.",
		FailureNarrative:      "Focus order does not preserve meaning and operability.",
		LimitationNote:        "Complete focus order evaluation requires manual keyboard navigation testing.",
		ManualTestingRequired: true,
	},
	"2.4.4": {
		SCID: "2.4.4", SCName: "Link Purpose (In Context)", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.4",
		SupportNarrative:      "All links have accessible names that describe their purpose.",
		PartialNarrative:      "Some links have ambiguous names (e.g., 'click here', 'read more') without sufficient context.",
		FailureNarrative:      "Many links lack accessible names or have ambiguous names without context.",
		LimitationNote:        "Contextual link purpose evaluation requires manual review of surrounding content.",
		ManualTestingRequired: true,
	},
	"2.4.5": {
		SCID: "2.4.5", SCName: "Multiple Ways", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.2.4.5",
		LimitationNote: "Multiple means of navigation (search, site map, related links) require multi-page manual evaluation.",
		NotAutomatable: true,
	},
	"2.4.6": {
		SCID: "2.4.6", SCName: "Headings and Labels", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.6",
		SupportNarrative:      "Headings and form labels appear descriptive.",
		PartialNarrative:      "Some headings or labels may not adequately describe topic or purpose.",
		FailureNarrative:      "Headings or labels are missing or do not describe topic or purpose.",
		LimitationNote:        "Meaningfulness of heading and label text requires manual content review.",
		ManualTestingRequired: true,
	},
	"2.4.7": {
		SCID: "2.4.7", SCName: "Focus Visible", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.2.4.7",
		SupportNarrative:      "Keyboard focus indicators are visible on interactive elements.",
		PartialNarrative:      "Focus indicators are absent or insufficient on some interactive elements.",
		FailureNarrative:      "No visible keyboard focus indicators detected on interactive elements.",
		LimitationNote:        "Focus visibility testing requires manual keyboard navigation. CSS :focus styles may be overridden by OS themes.",
		ManualTestingRequired: true,
	},
	"2.5.1": {
		SCID: "2.5.1", SCName: "Pointer Gestures", Level: "A", WCAGVersion: "2.1",
		EN301549Clause:        "9.2.5.1",
		SupportNarrative:      "Multi-point and path-based gestures have single-pointer alternatives.",
		PartialNarrative:      "Some multi-point or path-based gesture functionality lacks single-pointer alternatives.",
		FailureNarrative:      "Functionality requiring multi-point or path-based gestures lacks alternatives.",
		LimitationNote:        "Gesture detection is heuristic. Manual testing on touch devices required.",
		ManualTestingRequired: true,
	},
	"2.5.2": {
		SCID: "2.5.2", SCName: "Pointer Cancellation", Level: "A", WCAGVersion: "2.1",
		EN301549Clause:        "9.2.5.2",
		LimitationNote:        "Evaluating whether single-pointer events are activated on down-event and whether a mechanism to abort or undo is provided requires manual interaction testing. Automated scanning cannot observe runtime pointer event sequences.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"2.5.3": {
		SCID: "2.5.3", SCName: "Label in Name", Level: "A", WCAGVersion: "2.1",
		EN301549Clause:        "9.2.5.3",
		SupportNarrative:      "Accessible names of labeled controls contain the visible label text.",
		PartialNarrative:      "Some controls have accessible names that do not include the visible label text.",
		FailureNarrative:      "Controls have accessible names that do not match visible label text, breaking voice control.",
		LimitationNote:        "Label-in-name verification for dynamically generated or styled content may require manual review.",
		ManualTestingRequired: false,
	},
	"2.5.4": {
		SCID: "2.5.4", SCName: "Motion Actuation", Level: "A", WCAGVersion: "2.1",
		EN301549Clause: "9.2.5.4",
		LimitationNote: "Device motion and orientation events require manual testing on physical devices.",
		NotAutomatable: true,
	},
	"3.1.1": {
		SCID: "3.1.1", SCName: "Language of Page", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.1.1",
		SupportNarrative:      "The html element has a valid lang attribute.",
		PartialNarrative:      "The html element is missing a lang attribute or has an invalid language code.",
		FailureNarrative:      "The page language is not programmatically determinable.",
		ManualTestingRequired: false,
	},
	"3.1.2": {
		SCID: "3.1.2", SCName: "Language of Parts", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.1.2",
		SupportNarrative:      "Content in languages other than the primary page language uses lang attributes.",
		PartialNarrative:      "Some multi-language content passages lack lang attributes.",
		FailureNarrative:      "Multi-language content does not use lang attributes to identify language changes.",
		LimitationNote:        "Language of parts requires manual review of multilingual content.",
		ManualTestingRequired: true,
	},
	"3.2.1": {
		SCID: "3.2.1", SCName: "On Focus", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.2.1",
		SupportNarrative:      "No context changes triggered solely by keyboard focus detected.",
		PartialNarrative:      "Some focus events may trigger unexpected context changes.",
		FailureNarrative:      "Context changes triggered by focus detected.",
		LimitationNote:        "Focus-triggered context changes require manual keyboard navigation testing.",
		ManualTestingRequired: true,
	},
	"3.2.2": {
		SCID: "3.2.2", SCName: "On Input", Level: "A", WCAGVersion: "2.0",
		EN301549Clause: "9.3.2.2",
		LimitationNote: "Input-triggered context changes require manual interaction testing.",
		NotAutomatable: true,
	},
	"3.2.3": {
		SCID: "3.2.3", SCName: "Consistent Navigation", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.3.2.3",
		LimitationNote: "Requires multi-page manual testing to verify navigation consistency across the site.",
		NotAutomatable: true,
	},
	"3.2.4": {
		SCID: "3.2.4", SCName: "Consistent Identification", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.3.2.4",
		LimitationNote: "Requires multi-page manual testing to verify consistent labeling of identical functionality.",
		NotAutomatable: true,
	},
	"3.3.1": {
		SCID: "3.3.1", SCName: "Error Identification", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.3.1",
		SupportNarrative:      "Form errors are identified in text and describe the item in error.",
		PartialNarrative:      "Some form errors may not be programmatically identified or may not describe the error in text.",
		FailureNarrative:      "Form errors are not identified in text.",
		LimitationNote:        "Dynamic error states require manual form submission testing.",
		ManualTestingRequired: true,
	},
	"3.3.2": {
		SCID: "3.3.2", SCName: "Labels or Instructions", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.3.2",
		SupportNarrative:      "Form inputs have associated labels or instructions.",
		PartialNarrative:      "Some form inputs lack associated labels or instructions.",
		FailureNarrative:      "Form inputs generally lack associated labels or instructions.",
		ManualTestingRequired: false,
	},
	"3.3.3": {
		SCID: "3.3.3", SCName: "Error Suggestion", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause:        "9.3.3.3",
		LimitationNote:        "Evaluating whether error messages include helpful suggestions for correction requires manual form interaction and content review. Automated scanning can detect error elements but cannot judge the quality or relevance of suggestion text.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"3.3.4": {
		SCID: "3.3.4", SCName: "Error Prevention (Legal, Financial, Data)", Level: "AA", WCAGVersion: "2.0",
		EN301549Clause: "9.3.3.4",
		LimitationNote: "Requires manual testing with domain knowledge to verify error prevention mechanisms for consequential actions (purchases, legal submissions, financial transactions).",
		NotAutomatable: true,
	},
	"4.1.1": {
		SCID: "4.1.1", SCName: "Parsing", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.4.1.1",
		SupportNarrative:      "HTML parsing errors that affect accessibility were not detected.",
		PartialNarrative:      "Some HTML parsing errors detected that may affect assistive technology processing.",
		FailureNarrative:      "Significant HTML parsing errors detected that are likely to cause assistive technology failures.",
		ManualTestingRequired: false,
	},
	"4.1.2": {
		SCID: "4.1.2", SCName: "Name, Role, Value", Level: "A", WCAGVersion: "2.0",
		EN301549Clause:        "9.4.1.2",
		SupportNarrative:      "Automated testing verified ARIA roles, states, properties, and accessible names for interactive components.",
		PartialNarrative:      "Some interactive components have missing or incorrect ARIA attributes.",
		FailureNarrative:      "A majority of interactive components have ARIA violations, significantly impeding assistive technology users.",
		LimitationNote:        "Dynamic state changes triggered by user interaction require manual testing with assistive technologies.",
		ManualTestingRequired: true,
	},
	"4.1.3": {
		SCID: "4.1.3", SCName: "Status Messages", Level: "AA", WCAGVersion: "2.1",
		EN301549Clause:        "9.4.1.3",
		LimitationNote:        "Verifying that all status messages (e.g. form submissions, loading indicators, search results counts) are programmatically determinable through role or property without receiving focus requires manual screen reader testing. Automated scanning cannot verify the timing and announcement of dynamic content.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	// ── WCAG 2.2 Success Criteria ─────────────────────────────────────────────
	// Added after commit 2148e2c which added the scanner rules and WCAGMap entries.
	// The SCRegistry skip (score.go:374) is removed in the scoring step.
	"2.4.11": {
		SCID: "2.4.11", SCName: "Focus Not Obscured (Minimum)", Level: "AA", WCAGVersion: "2.2",
		EN301549Clause:        "9.2.4.11",
		SupportNarrative:      "Focused elements are not fully hidden by author-created sticky/fixed content.",
		PartialNarrative:      "Some focused elements are partially obscured by fixed or sticky content.",
		FailureNarrative:      "Focused elements are fully hidden behind fixed or sticky header/footer content.",
		LimitationNote:        "Heuristic detection of focus obscurement uses Puppeteer overlay checks. Scrolling behaviour under complex layouts may require manual keyboard navigation testing.",
		ManualTestingRequired: true,
	},
	"2.4.13": {
		SCID: "2.4.13", SCName: "Focus Appearance", Level: "AAA", WCAGVersion: "2.2",
		EN301549Clause:        "9.2.4.13",
		SupportNarrative:      "Focus indicators meet minimum area and contrast requirements.",
		PartialNarrative:      "Some focus indicators do not meet the minimum area or contrast requirements.",
		FailureNarrative:      "Focus indicators fail area or contrast requirements on most interactive elements.",
		LimitationNote:        "Contrast and area measurement for custom focus indicators requires Puppeteer-based evaluation and may need manual verification for complex CSS states.",
		ManualTestingRequired: true,
	},
	"2.5.7": {
		SCID: "2.5.7", SCName: "Dragging Movements", Level: "AA", WCAGVersion: "2.2",
		EN301549Clause:        "9.2.5.7",
		SupportNarrative:      "All drag-and-drop functionality has a single-pointer alternative.",
		PartialNarrative:      "Some drag-and-drop operations lack single-pointer alternatives.",
		FailureNarrative:      "Drag-and-drop functionality detected without a single-pointer alternative.",
		LimitationNote:        "Detection of drag interfaces is DOM-heuristic. Functional testing of alternatives requires manual interaction.",
		ManualTestingRequired: true,
	},
	"2.5.8": {
		SCID: "2.5.8", SCName: "Target Size (Minimum)", Level: "AA", WCAGVersion: "2.2",
		EN301549Clause:        "9.2.5.8",
		SupportNarrative:      "All interactive targets meet the 24×24 CSS pixel minimum size requirement.",
		PartialNarrative:      "Some interactive targets are smaller than the 24×24 CSS pixel minimum.",
		FailureNarrative:      "Widespread target-size failures detected; many interactive elements are smaller than 24×24px.",
		LimitationNote:        "Target size is measured from the bounding box of the element. Inline link targets and spacing offsets may require manual verification.",
		ManualTestingRequired: false,
	},
	"3.2.6": {
		SCID: "3.2.6", SCName: "Consistent Help", Level: "A", WCAGVersion: "2.2",
		EN301549Clause:        "9.3.2.6",
		LimitationNote:        "Verifying that help mechanisms (contact details, chat, FAQ links) appear in the same relative order across multiple pages requires multi-page manual comparison. The scanner rule (`consistent-help`) is always incomplete — it can detect a help element on one page but cannot verify consistency across the site.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"3.3.7": {
		SCID: "3.3.7", SCName: "Redundant Entry", Level: "A", WCAGVersion: "2.2",
		EN301549Clause:        "9.3.3.7",
		LimitationNote:        "Determining whether users are asked to re-enter information already provided in the same process requires manual interaction testing across multi-step forms. The scanner rule (`redundant-entry`) is always incomplete — it can detect multi-step form patterns but cannot evaluate the actual data flow.",
		ManualTestingRequired: true,
		NotAutomatable:        true,
	},
	"3.3.8": {
		SCID: "3.3.8", SCName: "Accessible Authentication (Minimum)", Level: "AA", WCAGVersion: "2.2",
		EN301549Clause:        "9.3.3.8",
		SupportNarrative:      "No authentication mechanisms relying solely on cognitive function tests (e.g. remembering a password without alternatives) were detected.",
		PartialNarrative:      "Some authentication steps may impose cognitive function tests without an accessible alternative.",
		FailureNarrative:      "Authentication requires solving a cognitive function test (e.g. CAPTCHA without alternative) with no accessible alternative mechanism.",
		LimitationNote:        "CAPTCHA detection is heuristic. Fully evaluating authentication flows — including whether alternatives like copy-paste or object-recognition are available — requires manual testing.",
		ManualTestingRequired: true,
	},
}
