package models

// WCAGMap maps axe‑core rule IDs to the WCAG 2.1 success‑criterion numbers they satisfy.
// A rule can cover multiple criteria, therefore the value is a slice.
var WCAGMap = map[string][]string{
    // Core AXE rules (partial list – extend as needed)
    "accesskeys":                {"2.4.1"},
    "aria-allowed-attr":         {"4.1.2"},
    "aria-allowed-role":         {"4.1.2"},
    "aria-conditional-attr":     {"4.1.2"},
    "aria-deprecated-role":      {"4.1.2"},
    "aria-hidden-body":          {"1.3.2"},
    "aria-prohibited-attr":      {"4.1.2"},
    "aria-required-attr":        {"4.1.2"},
    "aria-roles":                {"4.1.1"},
    "aria-valid-attr-value":     {"4.1.2"},
    "aria-valid-attr":           {"4.1.2"},
    "autocomplete-valid":        {"1.3.5"},
    "avoid-inline-spacing":      {"1.4.12"},
    "button-name":               {"2.5.3"},
    "bypass":                    {"2.4.1"},
    "color-contrast":            {"1.4.3"},
    "document-title":            {"2.4.2"},
    "duplicate-id-aria":         {"4.1.1"},
    "empty-heading":             {"2.4.6"},
    "form-field-multiple-labels": {"3.3.2"},
    "heading-order":             {"2.4.10"},
    "html-has-lang":             {"3.1.1"},
    "html-lang-valid":           {"3.1.2"},
    "image-alt":                 {"1.1.1"},
    "image-redundant-alt":       {"1.1.1"},
    "label-title-only":          {"1.3.1"},
    "label":                     {"1.3.1"},
    "landmark-contentinfo-is-top-level": {"1.3.1"},
    "landmark-main-is-top-level": {"1.3.1"},
    "landmark-no-duplicate-contentinfo": {"1.3.1"},
    "landmark-no-duplicate-main": {"1.3.1"},
    "landmark-one-main":         {"1.3.1"},
    "landmark-unique":           {"1.3.1"},
    "link-name":                 {"2.4.4"},
    "list":                      {"1.3.1"},
    "listitem":                  {"1.3.1"},
    "meta-viewport-large":       {"1.4.10"},
    "meta-viewport":             {"1.4.10"},
    "nested-interactive":        {"2.1.1"},
    "page-has-heading-one":      {"2.4.6"},
    "presentation-role-conflict": {"4.1.2"},
    "region":                    {"1.3.1"},
    "select-name":               {"1.3.1"},
    "valid-lang":                {"3.1.1"},
    // Custom checks added in scripts/axe_runner.js
    "g58-link-to-text-alternative": {"1.2.1"},
    "h53-media-description":        {"1.2.3"},
}
